apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-sm
  namespace: default
  labels:
    serviceMonitorSelector: prometheus
spec:
  endpoints:
    - port: web
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      operated-prometheus: "true"
